sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234

  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tMw518yH5HUHbJibeSY
    access-key-secret: hiC8vqArE6VevQbJ86LukxzXwKVGm2
    bucket-name: sky-58269

  redis:
    host: localhost
    port: 6379
    auth: "123456"
    database: 0

  wechat:
    appid: wx81ebad218b2943e5
    secret: 20c4133bd1a5d434905539da552f9645
    mchid:
    mch-serial-no:
    private-key-file-path:
    api-v3-key:
    we-chat-pay-cert-file-path:
    notify-url:
    refund-notify-url: